apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreact
  template:
    metadata:
      labels:
        app: myreact
    spec:
      containers:
        - name: react-container
          image: ashish200214/reactapp:fullyfinal1
          ports:
            - containerPort: 5173
